name: 311PhoneRepair
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fed44a'
    - '#d41a39'
    - '#676767'
    - '#121212'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
